[package]
name = "trashy_bot"
version = "0.1.0"
authors = ["Denis Richartz <denisrichartz92@gmail.com>"]
edition = "2018"

[dependencies]
kankyo = "0.2.0"

[dependencies.serenity]
version = "0.5.12"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
] # unused features [ "voice" ]