[package]
name = "trashy_bot"
version = "0.3.0"
authors = ["Denis Richartz <denisrichartz92@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
rand = "0.7"
chrono = "0.4"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls", "stream"] }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
tokio-postgres = { version = "0.5", features = ["with-serde_json-1", "with-chrono-0_4"] }
deadpool-postgres = "0.5.4"
deadpool = "0.5.1"
refinery = { version = "0.2", features = ["tokio-postgres"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2.3", features = ["env-filter"] }
tracing-futures = "0.2.3"
tantivy = "0.13"

[dependencies.serenity]
git = "https://github.com/ikkerens/serenity"
branch = "bugfix/io-error-ignored-fix"
default-features = false
features = [
    "builder",
    "cache",
    "collector",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]