[package]
name = "trashy_bot"
version = "0.3.0"
authors = ["Denis Richartz <denisrichartz92@gmail.com>"]
edition = "2018"

[dependencies]
kankyo = "0.2.0"
rand = "0.6"
diesel = { version = "1.0.0", features = ["postgres", "chrono", "r2d2", "serde_json"] }
chrono = "*"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
fern = "0.5"
regex = "1"
lazy_static = "1.3.0"
itertools = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.9"
hey_listen = "0.4.0"
time = "0.1"
tokio = "0.2.0-alpha.4"

[dependencies.serenity]
version = "0.7.0"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "voice",
]