[package]
name = "trashy_bot"
version = "0.3.0"
authors = ["Denis Richartz <denisrichartz92@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
rand = "0.7"
# diesel = { version = "1.0.0", features = ["postgres", "chrono", "r2d2", "serde_json"] }
chrono = "*"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
fern = "0.5"
regex = "1"
lazy_static = "1.4.0"
itertools = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
# time = "0.1"
tokio = { version = "0.2", features = ["full"] }
postgres = { version = "0.17", features = ["with-serde_json-1", "with-chrono-0_4"] }
r2d2 = "0.8.8"
r2d2_postgres = "0.16.0"
refinery = { version = "0.2", features = ["postgres"] }

[dependencies.serenity]
version = "0.8"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "voice",
]